# NumPy

conda install numpy

In [1]:
my_list=[1,2,3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(3)

array([0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [14]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.random.rand(2)

array([0.65383197, 0.82512552])

In [18]:
np.random.rand(5,5)

array([[0.11044659, 0.47861464, 0.09631033, 0.91767301, 0.31527539],
       [0.06012145, 0.11450845, 0.33696348, 0.94975617, 0.11921059],
       [0.37400011, 0.99897164, 0.53587079, 0.5365172 , 0.18271365],
       [0.49036481, 0.29044088, 0.49148962, 0.59717931, 0.3482847 ],
       [0.61042794, 0.76350094, 0.66984253, 0.29963043, 0.60804053]])

In [22]:
np.random.randn(5,5)

array([[ 0.81371607, -0.7248381 , -0.76453528,  0.83494447,  0.05621413],
       [-0.22638663, -1.47756308, -0.64022879, -0.91457791, -0.03071903],
       [ 1.35829034,  0.52203132,  0.36267794, -0.07270966,  0.21943773],
       [-0.28927107,  0.87055106, -1.458204  ,  0.11544045, -0.95570884],
       [ 0.32614183,  1.03803658, -0.88920135,  0.07596261, -0.59307416]])

In [29]:
np.random.randint(1,10)

2

In [30]:
np.random.randint(1,10,10)

array([3, 6, 5, 1, 9, 7, 5, 7, 2, 6])

In [32]:
tab=np.arange(25)

In [33]:
tab

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
tabint=np.random.randint(0,50,10)

In [35]:
tabint

array([35, 39, 36, 46, 33, 17, 23, 10, 20, 18])

In [36]:
tab.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
tabint.min()

10

In [38]:
tabint.max()

46

In [39]:
tabint.argmin()

7

In [40]:
tabint.argmax()

3

In [44]:
tab.shape

(25,)

In [45]:
tab.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [46]:
tab2=tab.reshape(5,5)

In [47]:
tab2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
tab2.shape

(5, 5)

In [51]:
tab.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [52]:
tab.dtype

dtype('int32')